--SELECT COUNT(*) FROM customer_purchases
select TOP 12 * from customer_purchases

--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount_usd) AS total_sales_usd 
FROM customer_purchases 
GROUP BY gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount_usd 
FROM customer_purchases 
WHERE discount_applied = 'Yes' 
AND purchase_amount_usd >= (SELECT AVG(purchase_amount_usd) FROM customer_purchases)

--Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 item_purchased, ROUND(AVG(review_rating), 1) AS average_rating
FROM customer_purchases 
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, AVG(purchase_amount_usd) AS average_purchase_amount
FROM customer_purchases 
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT 
subscription_status, 
COUNT(customer_id) AS total_customers,
SUM(purchase_amount_usd) AS total_purchases_usd, 
CAST((SELECT AVG(purchase_amount_usd * 1.0) FROM customer_purchases) AS DECIMAL(10,2)) AS average_purchase_usd
FROM customer_purchases
GROUP BY subscription_status
ORDER BY total_purchases_usd, average_purchase_usd DESC;

--Non-subscribed customers spend more than subscribed cux

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
--We need ratio, (Discounted Sales / Total Sales) * 100
SELECT TOP 5 item_purchased,
CAST(
	(SUM(CASE WHEN discount_applied = 'Yes' THEN 1.0 ELSE 0.0 END)--if 'Yes' then it'll get added by SUM()
	/ COUNT(*)) * 100.0
AS DECIMAL(10,2)) AS discount_rate
FROM customer_purchases
GROUP BY item_purchased
ORDER BY discount_rate DESC;
--Hats need most discount 50% of the sales when discount applied

--and I noticed there are NULL in purchase_frequency_days, so fixing it before solving next que
UPDATE customer_purchases SET customer_purchases.purchase_frequency_days = 
	CASE frequency_of_purchases
		WHEN 'Fortnightly' THEN 14
		WHEN 'Monthly' THEN 30
		WHEN 'Weekly' THEN 7
		WHEN 'Bi-Weekly' THEN 14
		WHEN 'Quarterly' THEN 90
		WHEN 'Every 3 Months' THEN 90
		WHEN 'Annually' THEN 365
		ELSE NULL
	END;

SELECT DISTINCT purchase_frequency_days FROM customer_purchases; --check if done correctly

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
--and show the count of each segment.
WITH customer_cte AS (
SELECT customer_id, previous_purchases,
	CASE 
		WHEN previous_purchases = 1 THEN 'New'
		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		ELSE 'Loyal'
	END as customer_segment
FROM customer_purchases
)

SELECT customer_segment, COUNT(*) 
FROM customer_cte
GROUP BY customer_segment

--Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_purchases
    GROUP BY category, item_purchased
)
SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    subscription_status,
    COUNT(*) AS repeat_buyers
FROM customer_purchases
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY COUNT(*) DESC;

--Q10. What is the revenue contribution of each age group?
SELECT 
    age_group,
    SUM(purchase_amount_usd) AS total_revenue
FROM customer_purchases
GROUP BY age_group
ORDER BY total_revenue DESC;